services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
  
  doclinic-frontend:
    image: cristianoaguiarofc/doclinic-frontend
    ports:
      - 4200:4200
    networks:
      - app-network
  
  doclinic-backend:
    image: cristianoaguiarofc/doclinic
    ports:
      - 8086:8086
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
