name: Build VPS Server

on:
  push:
    branches:
      - master  # Ajuste para o branch que você deseja monitorar
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-vps-server:
    runs-on: ubuntu-latest
    steps:
      # Configurar a autenticação para GitHub
      - name: Set up GitHub credentials
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.GITHUB_ACTOR }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      # Deploy no VPS usando SSH
      - name: Build VPS Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            rm -rf scheduling-controller-cd
            git clone https://github.com/scheduling-controller/scheduling-controller-cd.git
            cd scheduling-controller-cd

            docker compose down
            docker compose up -d